ALTER TABLE `Branch`
  ADD COLUMN `city` VARCHAR(191) NULL,
  ADD COLUMN `state` VARCHAR(191) NULL,
  ADD COLUMN `country` VARCHAR(191) NULL;

ALTER TABLE `User`
  ADD COLUMN `moduleAccess` JSON NULL;
