ALTER TABLE `WalletAccount`
  ADD COLUMN `reservedBalance` DECIMAL(14,2) NOT NULL DEFAULT 0.00;

CREATE TABLE `FinancialSettlement` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `walletAccountId` VARCHAR(191) NOT NULL,
  `sourceType` VARCHAR(64) NOT NULL,
  `sourceId` VARCHAR(191) NOT NULL,
  `method` ENUM('MANUAL','PROVIDER') NOT NULL,
  `status` ENUM('PREPARED','RESERVED','PROVIDER_PROCESSING','UNKNOWN','SUCCEEDED','FAILED','REVERSED') NOT NULL DEFAULT 'PREPARED',
  `amount` DECIMAL(14,2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'NGN',
  `internalReference` VARCHAR(191) NOT NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `beneficiarySnapshot` JSON NULL,
  `provider` VARCHAR(32) NULL,
  `providerRecipientReference` VARCHAR(191) NULL,
  `providerTransferReference` VARCHAR(191) NULL,
  `externalReference` VARCHAR(191) NULL,
  `evidence` JSON NULL,
  `failureReason` TEXT NULL,
  `reservationReleasedAt` DATETIME(3) NULL,
  `reservedAt` DATETIME(3) NULL,
  `providerProcessingAt` DATETIME(3) NULL,
  `settledAt` DATETIME(3) NULL,
  `reversedAt` DATETIME(3) NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `FinancialSettlement_org_source_key` (`organizationId`, `sourceType`, `sourceId`),
  UNIQUE INDEX `FinancialSettlement_org_idempotency_key` (`organizationId`, `idempotencyKey`),
  UNIQUE INDEX `FinancialSettlement_org_internal_ref_key` (`organizationId`, `internalReference`),
  UNIQUE INDEX `FinancialSettlement_org_external_ref_key` (`organizationId`, `externalReference`),
  UNIQUE INDEX `FinancialSettlement_provider_transfer_key` (`provider`, `providerTransferReference`),
  INDEX `FinancialSettlement_org_status_created_idx` (`organizationId`, `status`, `createdAt`),
  INDEX `FinancialSettlement_wallet_status_idx` (`walletAccountId`, `status`),
  CONSTRAINT `FinancialSettlement_org_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FinancialSettlement_wallet_fkey` FOREIGN KEY (`walletAccountId`) REFERENCES `WalletAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
