ALTER TABLE `PayrollRun`
  ADD COLUMN `employeeCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `totalGross` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalPaye` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalPension` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalEmployerPension` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalNhf` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalLoans` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalOtherDeductions` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `totalNetPay` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `computedAt` DATETIME(3) NULL,
  ADD COLUMN `approvedAt` DATETIME(3) NULL,
  ADD COLUMN `approvedById` VARCHAR(191) NULL,
  ADD COLUMN `disbursedAt` DATETIME(3) NULL;

ALTER TABLE `Payslip`
  ADD COLUMN `employeeNoSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `employeeNameSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `roleSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `bankSnapshot` JSON NULL,
  ADD COLUMN `loanDeduction` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `customDeduction` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `paymentStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING';
