import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { evaluateUnifiedPayeeEligibility } from "./payroll.service";
import { payrollPayRunCreateSchema } from "./payroll.validation";

const periodStart = new Date("2026-10-01T00:00:00.000Z");
const periodEnd = new Date("2026-10-31T23:59:59.999Z");
const external = (overrides: Record<string, unknown> = {}) => ({ id: "p1", organizationId: "o1", type: "CONTRACT", taxRegime: "WHT", status: "ACTIVE", deletedAt: null, externalOnPayroll: true, name: "External Payee", monthlyAmount: 100000, dateOnboarded: null, employee: null, ...overrides });
const permanent = (overrides: Record<string, unknown> = {}) => ({ id: "p2", organizationId: "o1", type: "PERMANENT", taxRegime: "PAYE", deletedAt: null, employee: { status: "ACTIVE", lifecycleStatus: "CONFIRMED", hireDate: new Date("2026-01-01T00:00:00.000Z"), payrollEnrollment: { isActive: true, enrolledAt: new Date("2026-01-01T00:00:00.000Z"), removedAt: null }, salaryStructures: [{}] }, ...overrides });

test("pay-run creation defaults to ALL_ELIGIBLE and accepts EMPTY", () => { assert.equal(payrollPayRunCreateSchema.parse({ periodLabel: "October", from: "2026-10-01", to: "2026-10-31" }).selectionMode, "ALL_ELIGIBLE"); assert.equal(payrollPayRunCreateSchema.parse({ periodLabel: "October", from: "2026-10-01", to: "2026-10-31", selectionMode: "EMPTY" }).selectionMode, "EMPTY"); });
test("Permanent eligibility gives EXITED lifecycle precedence", () => { assert.deepEqual(evaluateUnifiedPayeeEligibility(permanent(), periodStart, periodEnd), []); assert.ok(evaluateUnifiedPayeeEligibility(permanent({ employee: { ...permanent().employee, lifecycleStatus: "EXITED" } }), periodStart, periodEnd).includes("EMPLOYEE_EXITED")); });
test("Permanent eligibility requires active enrollment and effective salary", () => { assert.ok(evaluateUnifiedPayeeEligibility(permanent({ employee: { ...permanent().employee, payrollEnrollment: { isActive: false, enrolledAt: periodStart, removedAt: null }, salaryStructures: [] } }), periodStart, periodEnd).includes("PAYROLL_ENROLLMENT_INACTIVE")); assert.ok(evaluateUnifiedPayeeEligibility(permanent({ employee: { ...permanent().employee, salaryStructures: [] } }), periodStart, periodEnd).includes("SALARY_STRUCTURE_MISSING")); });
test("external eligibility enforces tax, participation, compensation and no mid-period proration", () => { assert.deepEqual(evaluateUnifiedPayeeEligibility(external(), periodStart, periodEnd), []); assert.ok(evaluateUnifiedPayeeEligibility(external({ dateOnboarded: new Date("2026-10-15T00:00:00.000Z") }), periodStart, periodEnd).includes("STARTS_DURING_PERIOD")); assert.ok(evaluateUnifiedPayeeEligibility(external({ externalOnPayroll: false }), periodStart, periodEnd).includes("NOT_ON_PAYROLL")); assert.ok(evaluateUnifiedPayeeEligibility(external({ taxRegime: "EXEMPT" }), periodStart, periodEnd).includes("INVALID_TAX_REGIME")); assert.deepEqual(evaluateUnifiedPayeeEligibility(external({ type: "CONSULTANT", taxRegime: "EXEMPT" }), periodStart, periodEnd), []); });
test("legacy Payees cannot enter unified membership", () => { assert.ok(evaluateUnifiedPayeeEligibility(external({ type: "CONTRACTOR", taxRegime: "LEGACY_UNSPECIFIED" }), periodStart, periodEnd).includes("LEGACY_RECLASSIFICATION_REQUIRED")); });
test("P2.1 creation is DRAFT-only and never enqueues calculation", () => { const source = fs.readFileSync(path.resolve("src/modules/payroll/payroll.service.ts"), "utf8"); const body = source.slice(source.indexOf("export const createAndComputePayRun"), source.indexOf("export const listPayRunParticipants")); assert.match(body, /status: "DRAFT"/); assert.match(body, /membershipVersion: "UNIFIED_PAYEE_V1"/); assert.doesNotMatch(body, /enqueuePayrollJob|initialize-pay-run|payrollCalculationBatch|payslip|payeePayment|financialSettlement|wallet/); });
test("migration is additive and preserves historical runs as LEGACY_EMPLOYEE", () => { const sql = fs.readFileSync(path.resolve("prisma/migrations/20261003100000_draft_pay_run_membership/migration.sql"), "utf8"); assert.match(sql, /DEFAULT 'LEGACY_EMPLOYEE'/); assert.match(sql, /CREATE TABLE `PayrollRunParticipant`/); assert.doesNotMatch(sql, /^\s*(DELETE FROM|TRUNCATE|DROP TABLE|UPDATE `PayrollRun`)/im); });
