ALTER TABLE `Payslip`
  ADD COLUMN `taxStateSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `taxAuthoritySnapshot` JSON NULL,
  ADD COLUMN `tinSnapshot` VARCHAR(191) NULL;

CREATE TABLE `PayrollTaxRemittance` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `payrollRunId` VARCHAR(191) NOT NULL,
  `period` CHAR(7) NOT NULL,
  `state` VARCHAR(191) NOT NULL,
  `authorityCode` VARCHAR(191) NOT NULL,
  `authorityName` VARCHAR(191) NULL,
  `employeeCount` INTEGER NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `dueDate` DATETIME(3) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'DUE',
  `remittedAt` DATETIME(3) NULL,
  `paymentReference` VARCHAR(191) NULL,
  `receiptReference` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `PayrollTaxRemittance_org_run_authority_key`(`organizationId`, `payrollRunId`, `authorityCode`),
  INDEX `PayrollTaxRemittance_org_period_status_idx`(`organizationId`, `period`, `status`),
  CONSTRAINT `PayrollTaxRemittance_org_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PayrollTaxRemittance_run_fkey` FOREIGN KEY (`payrollRunId`) REFERENCES `PayrollRun`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `WalletTransaction` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `walletAccountId` VARCHAR(191) NOT NULL,
  `payrollRunId` VARCHAR(191) NULL,
  `taxRemittanceId` VARCHAR(191) NULL,
  `type` VARCHAR(191) NOT NULL,
  `direction` VARCHAR(191) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `balanceBefore` DECIMAL(14,2) NOT NULL,
  `balanceAfter` DECIMAL(14,2) NOT NULL,
  `reference` VARCHAR(191) NOT NULL,
  `transferReference` VARCHAR(191) NULL,
  `description` VARCHAR(191) NOT NULL,
  `sourceType` VARCHAR(191) NULL,
  `sourceId` VARCHAR(191) NULL,
  `reversalOfId` VARCHAR(191) NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `WalletTransaction_org_reference_key`(`organizationId`, `reference`),
  UNIQUE INDEX `WalletTransaction_org_transfer_key`(`organizationId`, `transferReference`),
  UNIQUE INDEX `WalletTransaction_source_key`(`walletAccountId`, `sourceType`, `sourceId`, `type`),
  INDEX `WalletTransaction_org_created_idx`(`organizationId`, `createdAt`),
  INDEX `WalletTransaction_org_type_direction_idx`(`organizationId`, `type`, `direction`),
  CONSTRAINT `WalletTransaction_org_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WalletTransaction_wallet_fkey` FOREIGN KEY (`walletAccountId`) REFERENCES `WalletAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WalletTransaction_run_fkey` FOREIGN KEY (`payrollRunId`) REFERENCES `PayrollRun`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WalletTransaction_remittance_fkey` FOREIGN KEY (`taxRemittanceId`) REFERENCES `PayrollTaxRemittance`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WalletTransaction_reversal_fkey` FOREIGN KEY (`reversalOfId`) REFERENCES `WalletTransaction`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
