import assert from "node:assert/strict";
import {after,before,test} from "node:test";
import express from "express";
import {Prisma} from "@prisma/client";
import {prisma} from "../core/prisma.js";
import {assertSafeTestDatabase} from "../test-infrastructure/test-database.js";
import {getFinancialOperationsSummary,listAttentionSettlements,listAttentionWebhooks,listInboundRecovery,requeueDeadLetterWebhook,triggerFinancialRecovery} from "../modules/platform-admin/financial-operations.service.js";
import {financialOperationsRouter} from "../modules/platform-admin/financial-operations.routes.js";
import {errorMiddleware} from "../middleware/error.middleware.js";
import type {SettlementProvider} from "../core/settlement-provider.js";
import {runFinancialRecovery} from "../core/financial-recovery.js";

const enabled=Boolean(process.env.TEST_DATABASE_GUARD);if(enabled){assert.equal(process.env.NODE_ENV,"test");assert.equal(process.env.PAYSTACK_TRANSFERS_ENABLED,"false");assertSafeTestDatabase({databaseUrl:process.env.DATABASE_URL_ORIGINAL,testDatabaseUrl:process.env.DATABASE_URL,nodeEnv:process.env.NODE_ENV,destructive:true});}const it=enabled?test:test.skip;
const PREFIX="phase3e-ops-";let seq=0;const uid=(name:string)=>`${PREFIX}${name}-${Date.now()}-${seq++}`;const money=(v:Prisma.Decimal.Value)=>new Prisma.Decimal(v);
const clean=async()=>{await prisma.financialIntegrityFinding.deleteMany();await prisma.financialIntegrityScanRun.deleteMany();await prisma.financialReconciliationRun.deleteMany();await prisma.providerWebhookEvent.deleteMany();const orgs=await prisma.organization.findMany({where:{slug:{startsWith:PREFIX}},select:{id:true}});for(const org of orgs){await prisma.auditLog.deleteMany({where:{organizationId:org.id}});await prisma.auditLogChain.deleteMany({where:{organizationId:org.id}});await prisma.walletFundingAttempt.deleteMany({where:{organizationId:org.id}});await prisma.financialSettlement.deleteMany({where:{organizationId:org.id}});await prisma.walletTransaction.deleteMany({where:{organizationId:org.id}});await prisma.walletAccount.deleteMany({where:{organizationId:org.id}});await prisma.user.deleteMany({where:{organizationId:org.id}});await prisma.role.deleteMany({where:{organizationId:org.id}});await prisma.organization.delete({where:{id:org.id}});}};
const fixture=async()=>{const slug=uid("tenant");const organization=await prisma.organization.create({data:{name:slug,slug,currency:"NGN"}});const role=await prisma.role.create({data:{organizationId:organization.id,name:"Ops",isSystem:true}});const user=await prisma.user.create({data:{organizationId:organization.id,roleId:role.id,email:`${slug}@example.test`,passwordHash:"test",firstName:"Ops",lastName:"Admin",isPlatformAdmin:true}});const wallet=await prisma.walletAccount.create({data:{organizationId:organization.id,name:"Ops Wallet",purpose:"PRIMARY",currency:"NGN",balance:money(0)}});return{organization,user,wallet,auth:{id:user.id,organizationId:organization.id,email:user.email,roleId:role.id,isPlatformAdmin:true,permissions:["platform:financial-operations:view","platform:financial-operations:manage"] as never[]}};};
if(enabled)before(clean);if(enabled)after(async()=>{await clean();await prisma.$disconnect();});

it("Phase 3E health is deterministic for fresh, stale, partial, high, and critical evidence",async()=>{const now=new Date();const recovery=await prisma.financialReconciliationRun.create({data:{trigger:"TEST",status:"COMPLETED",completedAt:now}});const scan=await prisma.financialIntegrityScanRun.create({data:{trigger:"TEST",scannerVersion:"3E",status:"COMPLETED",completedAt:now}});assert.equal((await getFinancialOperationsSummary(now)).status,"HEALTHY");await prisma.financialIntegrityFinding.create({data:{deduplicationKey:uid("high"),evidenceFingerprint:uid("ev"),category:"TEST_HIGH",severity:"HIGH",status:"OPEN",resourceType:"TEST",resourceId:uid("resource"),firstScanRunId:scan.id,lastScanRunId:scan.id}});assert.equal((await getFinancialOperationsSummary(now)).status,"DEGRADED");await prisma.financialIntegrityFinding.create({data:{deduplicationKey:uid("critical"),evidenceFingerprint:uid("ev"),category:"TEST_CRITICAL",severity:"CRITICAL",status:"OPEN",resourceType:"TEST",resourceId:uid("resource"),firstScanRunId:scan.id,lastScanRunId:scan.id}});assert.equal((await getFinancialOperationsSummary(now)).status,"CRITICAL");await prisma.financialIntegrityFinding.deleteMany();await prisma.financialReconciliationRun.update({where:{id:recovery.id},data:{completedAt:new Date(now.getTime()-31*60_000)}});assert.equal((await getFinancialOperationsSummary(now)).status,"CRITICAL");await prisma.financialReconciliationRun.update({where:{id:recovery.id},data:{completedAt:now}});await prisma.financialReconciliationRun.create({data:{trigger:"TEST",status:"PARTIAL",completedAt:now,errors:1}});const partial=await getFinancialOperationsSummary(now);assert.equal(partial.status,"DEGRADED");assert.equal(partial.recovery.lastProblemRun?.status,"PARTIAL");});

it("Phase 3E surfaces sanitized settlement, webhook, and inbound recovery evidence",async()=>{const fx=await fixture();await prisma.financialSettlement.create({data:{organizationId:fx.organization.id,walletAccountId:fx.wallet.id,sourceType:"TEST",sourceId:uid("source"),method:"PROVIDER",status:"UNKNOWN",amount:money(10),currency:"NGN",internalReference:uid("internal"),idempotencyKey:uid("idem"),provider:"PAYSTACK",providerTransferReference:"full-sensitive-provider-reference",lastReconciliationError:"bounded failure"}});await prisma.providerWebhookEvent.create({data:{provider:"PAYSTACK",eventFingerprint:uid("fingerprint"),eventType:"transfer.success",providerReference:"full-sensitive-provider-reference",payload:{secret:"must-not-return"},status:"DEAD_LETTER",attempts:5,deadLetteredAt:new Date(),failureReason:"safe failure"}});await prisma.providerWebhookEvent.create({data:{provider:"PAYSTACK",eventFingerprint:uid("stale-fingerprint"),eventType:"transfer.failed",payload:{secret:"also-hidden"},status:"PROCESSING",attempts:1,processingLeaseExpiresAt:new Date(Date.now()-60_000)}});await prisma.walletFundingAttempt.create({data:{organizationId:fx.organization.id,walletAccountId:fx.wallet.id,provider:"PAYSTACK",reference:uid("funding-reference"),amount:money(20),currency:"NGN",status:"UNKNOWN"}});const settlements=await listAttentionSettlements({});const webhooks=await listAttentionWebhooks({});const inbound=await listInboundRecovery({kind:"wallet-funding"});assert.equal(settlements.settlements.some(row=>row.id&&row.providerReferenceFingerprint&&!('providerTransferReference' in row)),true);assert.equal(webhooks.webhooks.some(row=>row.status==="DEAD_LETTER"&&row.providerReferenceFingerprint&&!('payload' in row)),true);assert.equal(webhooks.webhooks.some(row=>row.status==="PROCESSING"&&row.processingLeaseExpiresAt&&row.processingLeaseExpiresAt<new Date()),true);assert.equal(inbound.attempts.some(row=>"walletAccountId" in row&&row.walletAccountId===fx.wallet.id&&row.referenceFingerprint),true);assert.doesNotMatch(JSON.stringify({settlements,webhooks,inbound}),/full-sensitive-provider-reference|must-not-return|also-hidden/);});

it("Phase 3E concurrent dead-letter requeue preserves one event and one audit",async()=>{const fx=await fixture();const event=await prisma.providerWebhookEvent.create({data:{provider:"PAYSTACK",eventFingerprint:uid("retry-fingerprint"),eventType:"transfer.failed",payload:{reference:"safe"},status:"DEAD_LETTER",attempts:5,deadLetteredAt:new Date()}});const results=await Promise.all([requeueDeadLetterWebhook(event.id,fx.auth),requeueDeadLetterWebhook(event.id,fx.auth)]);assert.equal(results.every(row=>row.id===event.id),true);assert.equal(await prisma.providerWebhookEvent.count({where:{id:event.id}}),1);assert.equal((await prisma.providerWebhookEvent.findUniqueOrThrow({where:{id:event.id}})).status,"FAILED");assert.equal(await prisma.auditLog.count({where:{organizationId:fx.organization.id,action:"FINANCIAL_WEBHOOK_REQUEUED",resourceId:event.id}}),1);});

it("Phase 3E manual recovery overlaps Cron safely, is audited, and never calls provider for an empty batch",async()=>{await prisma.providerWebhookEvent.deleteMany();await prisma.financialSettlement.deleteMany();const fx=await fixture();let providerCalls=0;const provider:SettlementProvider={resolveAccount:async()=>{providerCalls++;throw new Error("unexpected")},createRecipient:async()=>{providerCalls++;throw new Error("unexpected")},initiateTransfer:async()=>{providerCalls++;throw new Error("unexpected")},finalizeTransferOtp:async()=>{providerCalls++;throw new Error("unexpected")},verifyTransfer:async()=>{providerCalls++;throw new Error("unexpected")},getBalance:async()=>{providerCalls++;throw new Error("unexpected")}};const [manual,cron]=await Promise.all([triggerFinancialRecovery(fx.auth,provider),runFinancialRecovery({trigger:"VERCEL_CRON",provider})]);assert.equal([manual.status,cron.status].every(status=>["COMPLETED","PARTIAL"].includes(status)),true);assert.equal(providerCalls,0);assert.equal(await prisma.auditLog.count({where:{organizationId:fx.organization.id,action:"FINANCIAL_RECOVERY_REQUESTED"}}),1);});

const serve=async(app:express.Express,fn:(base:string)=>Promise<void>)=>{const server=app.listen(0,"127.0.0.1");await new Promise<void>((resolve,reject)=>{server.once("listening",resolve);server.once("error",reject)});try{const address=server.address();if(!address||typeof address==="string")throw new Error("no address");await fn(`http://127.0.0.1:${address.port}`);}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))}};
const appFor=(user?:Record<string,unknown>)=>{const app=express();app.use(express.json());app.use((req,_res,next)=>{if(user)req.user=user as never;next()});app.use("/api/v1/platform-admin/financial-operations",financialOperationsRouter);app.use(errorMiddleware);return app;};
it("Phase 3E HTTP permissions separate operational reads from recovery actions",async()=>{const base={id:"u",organizationId:"o",email:"u@example.test",roleId:"r",isPlatformAdmin:true,permissions:[]};await serve(appFor(),async url=>assert.equal((await fetch(`${url}/api/v1/platform-admin/financial-operations/health`)).status,403));await serve(appFor(base),async url=>assert.equal((await fetch(`${url}/api/v1/platform-admin/financial-operations/health`)).status,403));await serve(appFor({...base,permissions:["platform:financial-operations:view"]}),async url=>{assert.equal((await fetch(`${url}/api/v1/platform-admin/financial-operations/health`)).status,200);assert.equal((await fetch(`${url}/api/v1/platform-admin/financial-operations/recovery-runs`,{method:"POST"})).status,403)});});
