CREATE TABLE `Payee` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
  `email` VARCHAR(191) NULL,
  `phone` VARCHAR(191) NULL,
  `bankName` VARCHAR(191) NULL,
  `bankCode` VARCHAR(191) NULL,
  `accountNumber` VARCHAR(191) NULL,
  `accountName` VARCHAR(191) NULL,
  `tin` VARCHAR(191) NULL,
  `monthlyAmount` DECIMAL(14,2) NOT NULL,
  `isTaxable` BOOLEAN NOT NULL DEFAULT false,
  `deletedAt` DATETIME(3) NULL,
  `removedByUserId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Payee_org_deleted_status_idx` (`organizationId`, `deletedAt`, `status`),
  INDEX `Payee_org_type_status_idx` (`organizationId`, `type`, `status`),
  INDEX `Payee_org_name_idx` (`organizationId`, `name`),
  CONSTRAINT `Payee_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PayeePayment` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `payrollRunId` VARCHAR(191) NOT NULL,
  `payeeId` VARCHAR(191) NOT NULL,
  `payeeNameSnapshot` VARCHAR(191) NOT NULL,
  `payeeTypeSnapshot` VARCHAR(191) NOT NULL,
  `grossAmount` DECIMAL(14,2) NOT NULL,
  `payeTax` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `netAmount` DECIMAL(14,2) NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'NGN',
  `isTaxableSnapshot` BOOLEAN NOT NULL,
  `bankSnapshot` JSON NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `paymentDate` DATETIME(3) NULL,
  `paymentReference` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PayeePayment_paymentReference_key` (`paymentReference`),
  UNIQUE INDEX `PayeePayment_run_payee_key` (`payrollRunId`, `payeeId`),
  INDEX `PayeePayment_org_payee_created_idx` (`organizationId`, `payeeId`, `createdAt`),
  INDEX `PayeePayment_org_status_idx` (`organizationId`, `status`),
  CONSTRAINT `PayeePayment_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PayeePayment_payrollRunId_fkey` FOREIGN KEY (`payrollRunId`) REFERENCES `PayrollRun` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PayeePayment_payeeId_fkey` FOREIGN KEY (`payeeId`) REFERENCES `Payee` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PayeeDocument` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `payeeId` VARCHAR(191) NOT NULL,
  `documentName` VARCHAR(191) NOT NULL,
  `fileReference` VARCHAR(191) NOT NULL,
  `originalName` VARCHAR(191) NOT NULL,
  `mimeType` VARCHAR(191) NOT NULL,
  `size` INTEGER NOT NULL,
  `uploadedById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `PayeeDocument_org_payee_created_idx` (`organizationId`, `payeeId`, `createdAt`),
  CONSTRAINT `PayeeDocument_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PayeeDocument_payeeId_fkey` FOREIGN KEY (`payeeId`) REFERENCES `Payee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
