CREATE TABLE `WalletFundingAttempt` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `walletAccountId` VARCHAR(191) NOT NULL,
  `provider` VARCHAR(191) NOT NULL DEFAULT 'PAYSTACK',
  `reference` VARCHAR(191) NOT NULL,
  `amount` DECIMAL(14, 2) NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'NGN',
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `authorizationUrl` TEXT NULL,
  `accessCode` VARCHAR(191) NULL,
  `providerReference` VARCHAR(191) NULL,
  `providerPayload` JSON NULL,
  `failureReason` TEXT NULL,
  `verifiedAt` DATETIME(3) NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `WalletFundingAttempt_reference_key`(`reference`),
  INDEX `WalletFundingAttempt_org_status_created_idx`(`organizationId`, `status`, `createdAt`),
  INDEX `WalletFundingAttempt_wallet_created_idx`(`walletAccountId`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `WalletFundingAttempt_org_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WalletFundingAttempt_wallet_fkey` FOREIGN KEY (`walletAccountId`) REFERENCES `WalletAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
