import { Router } from "express";
import multer from "multer";
import { asyncHandler } from "../../core/async-handler";
import { badRequest } from "../../core/http-error";
import { env } from "../../config/env";
import { validate } from "../../core/validate";
import { requireModuleEntitlement } from "../../middleware/module-access.middleware";
import { acknowledgeEmployeeAppraisalController, applyEmployeeLeaveController, assessEmployeeAppraisalGoalController, clockInEmployeeController, clockOutEmployeeController, confirmEmployeeAppraisalGoalsController, createEmployeeAppraisalGoalController, downloadEmployeeDocumentController, downloadEmployeePayslipController, getEmployeeAppraisalGoalsController, getEmployeeAppraisalHistoryDetailController, getEmployeeAppraisalOverviewController, getEmployeeAttendanceController, getEmployeeDashboardController, getEmployeeInboxController, getEmployeeLeaveController, getEmployeePayslipController, getEmployeePayslipsController, getEmployeeProfileController, getEmployeeSelfAssessmentController, listEmployeeAppraisalHistoryController, listEmployeeDocumentsController, listEmployeeRelieversController, raiseEmployeeAttendanceDisputeController, requestBankDetailsUpdateController, saveEmployeeSelfAssessmentDraftController, submitEmployeeSelfAssessmentController, updateEmployeePersonalDetailsController, updateEmployeeProfilePhotoController } from "./employee.controller";
import { bankUpdateRequestSchema, employeeAppraisalAcknowledgmentSchema, employeeAppraisalGoalConfirmationSchema, employeeAppraisalGoalCreateSchema, employeeAppraisalGoalParamsSchema, employeeAppraisalGoalUpdateSchema, employeeAppraisalHistoryQuerySchema, employeeAppraisalParamsSchema, employeeAttendanceDisputeSchema, employeeAttendanceParamsSchema, employeeAttendanceQuerySchema, employeeDashboardQuerySchema, employeeDocumentParamsSchema, employeeInboxQuerySchema, employeeLeaveQuerySchema, employeeLeaveRequestSchema, employeePayslipParamsSchema, employeePayslipsQuerySchema, employeeRelieverQuerySchema, employeeSelfAssessmentDraftSchema, updateEmployeePersonalDetailsSchema } from "./employee.validation";
export const employeeRouter = Router();
const profilePhotoUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.UPLOAD_MAX_FILE_SIZE_MB * 1024 * 1024, files: 1 }, fileFilter: (_req, file, callback) => { if (!["image/jpeg", "image/png", "image/webp"].includes(file.mimetype)) return callback(badRequest("Profile photo must be JPEG, PNG, or WebP")); return callback(null, true); } });
const receiveProfilePhoto = (req: any, res: any, next: any) => profilePhotoUpload.single("photo")(req, res, (error) => error instanceof multer.MulterError ? next(badRequest(error.code === "LIMIT_FILE_SIZE" ? `Profile photo must be <= ${env.UPLOAD_MAX_FILE_SIZE_MB}MB` : "Invalid profile photo upload")) : error ? next(error) : next());
employeeRouter.get("/payslips", requireModuleEntitlement("payroll"), validate({ query: employeePayslipsQuerySchema }), asyncHandler(getEmployeePayslipsController));
employeeRouter.get("/payslips/:payslipId/download", requireModuleEntitlement("payroll"), validate({ params: employeePayslipParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(downloadEmployeePayslipController));
employeeRouter.get("/payslips/:payslipId", requireModuleEntitlement("payroll"), validate({ params: employeePayslipParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(getEmployeePayslipController));
employeeRouter.use(requireModuleEntitlement("hris"));
employeeRouter.get("/dashboard", validate({ query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeDashboardController));
employeeRouter.get("/inbox", validate({ query: employeeInboxQuerySchema }), asyncHandler(getEmployeeInboxController));
employeeRouter.get("/attendance", validate({ query: employeeAttendanceQuerySchema }), asyncHandler(getEmployeeAttendanceController));
employeeRouter.post("/attendance/clock-in", validate({ body: employeeDashboardQuerySchema }), asyncHandler(clockInEmployeeController));
employeeRouter.post("/attendance/clock-out", validate({ body: employeeDashboardQuerySchema }), asyncHandler(clockOutEmployeeController));
employeeRouter.post("/attendance/:attendanceId/disputes", validate({ params: employeeAttendanceParamsSchema, body: employeeAttendanceDisputeSchema }), asyncHandler(raiseEmployeeAttendanceDisputeController));
employeeRouter.get("/leave", validate({ query: employeeLeaveQuerySchema }), asyncHandler(getEmployeeLeaveController));
employeeRouter.get("/leave/relievers", validate({ query: employeeRelieverQuerySchema }), asyncHandler(listEmployeeRelieversController));
employeeRouter.post("/leave/requests", validate({ body: employeeLeaveRequestSchema }), asyncHandler(applyEmployeeLeaveController));
employeeRouter.get("/appraisal", validate({ query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeAppraisalOverviewController));
employeeRouter.get("/appraisal/history", validate({ query: employeeAppraisalHistoryQuerySchema }), asyncHandler(listEmployeeAppraisalHistoryController));
employeeRouter.get("/appraisal/history/:appraisalId", validate({ params: employeeAppraisalParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeAppraisalHistoryDetailController));
employeeRouter.get("/appraisal/:appraisalId/goals", validate({ params: employeeAppraisalParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeAppraisalGoalsController));
employeeRouter.post("/appraisal/:appraisalId/goals", validate({ params: employeeAppraisalParamsSchema, body: employeeAppraisalGoalCreateSchema }), asyncHandler(createEmployeeAppraisalGoalController));
employeeRouter.patch("/appraisal/:appraisalId/goals/:goalId", validate({ params: employeeAppraisalGoalParamsSchema, body: employeeAppraisalGoalUpdateSchema }), asyncHandler(assessEmployeeAppraisalGoalController));
employeeRouter.post("/appraisal/:appraisalId/goals/confirm", validate({ params: employeeAppraisalParamsSchema, body: employeeAppraisalGoalConfirmationSchema }), asyncHandler(confirmEmployeeAppraisalGoalsController));
employeeRouter.get("/appraisal/:appraisalId/self-assessment", validate({ params: employeeAppraisalParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeSelfAssessmentController));
employeeRouter.put("/appraisal/:appraisalId/self-assessment/draft", validate({ params: employeeAppraisalParamsSchema, body: employeeSelfAssessmentDraftSchema }), asyncHandler(saveEmployeeSelfAssessmentDraftController));
employeeRouter.post("/appraisal/:appraisalId/self-assessment/submit", validate({ params: employeeAppraisalParamsSchema, body: employeeSelfAssessmentDraftSchema }), asyncHandler(submitEmployeeSelfAssessmentController));
employeeRouter.post("/appraisal/:appraisalId/acknowledge", validate({ params: employeeAppraisalParamsSchema, body: employeeAppraisalAcknowledgmentSchema }), asyncHandler(acknowledgeEmployeeAppraisalController));
employeeRouter.get("/profile", validate({ query: employeeDashboardQuerySchema }), asyncHandler(getEmployeeProfileController));
employeeRouter.patch("/profile/personal-details", validate({ body: updateEmployeePersonalDetailsSchema }), asyncHandler(updateEmployeePersonalDetailsController));
employeeRouter.patch("/profile/photo", receiveProfilePhoto, asyncHandler(updateEmployeeProfilePhotoController));
employeeRouter.get("/profile/documents", validate({ query: employeeDashboardQuerySchema }), asyncHandler(listEmployeeDocumentsController));
employeeRouter.get("/profile/documents/:documentId/download", validate({ params: employeeDocumentParamsSchema, query: employeeDashboardQuerySchema }), asyncHandler(downloadEmployeeDocumentController));
employeeRouter.post("/profile/bank-details/update-request", validate({ body: bankUpdateRequestSchema }), asyncHandler(requestBankDetailsUpdateController));
