import crypto from "node:crypto";
import { Prisma } from "@prisma/client";
import { env } from "../../config/env";
import { conflict, notFound } from "../../core/http-error";
import { prisma } from "../../core/prisma";
import { runFinancialRecovery } from "../../core/financial-recovery";
import { createAuditLog } from "../admin/admin.audit";
import type { AuthUser } from "../../types";
import type { SettlementProvider } from "../../core/settlement-provider";

const fingerprint=(value:string|null)=>value?crypto.createHash("sha256").update(value).digest("hex").slice(0,16):null;
const cutoff=(minutes:number,now=new Date())=>new Date(now.getTime()-minutes*60_000);
const page=(value:unknown,fallback:number,max:number)=>{const parsed=Number(value??fallback);if(!Number.isInteger(parsed)||parsed<1||parsed>max)throw conflict("Invalid pagination");return parsed;};
export const operationsPaging=(query:Record<string,unknown>)=>({page:page(query.page,1,1_000_000),limit:page(query.limit,20,100)});

export const getFinancialOperationsSummary=async(now=new Date())=>{
  const recoveryFreshAfter=cutoff(env.FINANCIAL_RECOVERY_FRESHNESS_MINUTES,now);
  const recoveryCriticalAfter=cutoff(env.FINANCIAL_RECOVERY_FRESHNESS_MINUTES*2,now);
  const integrityFreshAfter=cutoff(env.FINANCIAL_INTEGRITY_FRESHNESS_MINUTES,now);
  const integrityCriticalAfter=cutoff(env.FINANCIAL_INTEGRITY_FRESHNESS_MINUTES*2,now);
  const settlementStaleAt=new Date(now.getTime()-env.PAYSTACK_TRANSFER_STALE_MS);
  const [lastRecovery,lastRecoverySuccess,lastRecoveryProblem,lastScan,lastScanSuccess,lastScanProblem,criticalFindings,highFindings,settlementGroups,staleSettlements,webhookGroups,staleWebhooks,subscriptionRecoverable,fundingRecoverable]=await Promise.all([
    prisma.financialReconciliationRun.findFirst({orderBy:{startedAt:"desc"}}),
    prisma.financialReconciliationRun.findFirst({where:{status:"COMPLETED"},orderBy:{completedAt:"desc"}}),
    prisma.financialReconciliationRun.findFirst({where:{status:{in:["FAILED","PARTIAL"]}},orderBy:{startedAt:"desc"}}),
    prisma.financialIntegrityScanRun.findFirst({orderBy:{startedAt:"desc"}}),
    prisma.financialIntegrityScanRun.findFirst({where:{status:"COMPLETED"},orderBy:{completedAt:"desc"}}),
    prisma.financialIntegrityScanRun.findFirst({where:{status:{in:["FAILED","PARTIAL"]}},orderBy:{startedAt:"desc"}}),
    prisma.financialIntegrityFinding.count({where:{status:"OPEN",severity:"CRITICAL"}}),
    prisma.financialIntegrityFinding.count({where:{status:"OPEN",severity:"HIGH"}}),
    prisma.financialSettlement.groupBy({by:["status"],where:{status:{in:["PROVIDER_PROCESSING","UNKNOWN","FAILED","REVERSED"]}},_count:{_all:true}}),
    prisma.financialSettlement.count({where:{status:{in:["PROVIDER_PROCESSING","UNKNOWN"]},updatedAt:{lt:settlementStaleAt}}}),
    prisma.providerWebhookEvent.groupBy({by:["status"],where:{status:{in:["RECEIVED","PROCESSING","FAILED","DEAD_LETTER"]}},_count:{_all:true}}),
    prisma.providerWebhookEvent.count({where:{status:"PROCESSING",processingLeaseExpiresAt:{lt:now}}}),
    prisma.subscriptionPaymentAttempt.count({where:{OR:[{status:{in:["INITIALIZING","INITIALIZED","UNKNOWN","PROCESSING"]}},{reconciliationDeadLetteredAt:{not:null}}]}}),
    prisma.walletFundingAttempt.count({where:{OR:[{status:{in:["INITIALIZING","INITIALIZED","UNKNOWN","PROCESSING"]}},{reconciliationDeadLetteredAt:{not:null}}]}}),
  ]);
  const recoveryFresh=Boolean(lastRecoverySuccess?.completedAt&&lastRecoverySuccess.completedAt>=recoveryFreshAfter);
  const scannerFresh=Boolean(lastScanSuccess?.completedAt&&lastScanSuccess.completedAt>=integrityFreshAfter);
  const recoveryCritical=!lastRecoverySuccess?.completedAt||lastRecoverySuccess.completedAt<recoveryCriticalAfter;
  const scannerCritical=!lastScanSuccess?.completedAt||lastScanSuccess.completedAt<integrityCriticalAfter;
  const webhookCounts=Object.fromEntries(webhookGroups.map(row=>[row.status,row._count._all]));
  const settlementCounts=Object.fromEntries(settlementGroups.map(row=>[row.status,row._count._all]));
  const deadLetters=webhookCounts.DEAD_LETTER??0;
  const status=criticalFindings>0||recoveryCritical||scannerCritical||deadLetters>0||staleSettlements>0?"CRITICAL":highFindings>0||!recoveryFresh||!scannerFresh||lastRecovery?.status==="PARTIAL"||lastScan?.status==="PARTIAL"||staleWebhooks>0?"DEGRADED":"HEALTHY";
  return {status,checkedAt:now,thresholds:{recoveryFreshMinutes:env.FINANCIAL_RECOVERY_FRESHNESS_MINUTES,recoveryCriticalMinutes:env.FINANCIAL_RECOVERY_FRESHNESS_MINUTES*2,integrityFreshMinutes:env.FINANCIAL_INTEGRITY_FRESHNESS_MINUTES,integrityCriticalMinutes:env.FINANCIAL_INTEGRITY_FRESHNESS_MINUTES*2},recovery:{fresh:recoveryFresh,lastRun:lastRecovery,lastSuccessfulRun:lastRecoverySuccess,lastProblemRun:lastRecoveryProblem},integrity:{fresh:scannerFresh,lastRun:lastScan,lastSuccessfulRun:lastScanSuccess,lastProblemRun:lastScanProblem,openFindings:{critical:criticalFindings,high:highFindings}},settlements:{counts:settlementCounts,staleRecoverable:staleSettlements},webhooks:{counts:webhookCounts,staleProcessing:staleWebhooks},inboundRecovery:{subscriptionRecoverable,walletFundingRecoverable:fundingRecoverable}};
};

export const listRecoveryRuns=async(query:Record<string,unknown>)=>{const p=operationsPaging(query);const where:Prisma.FinancialReconciliationRunWhereInput={...(typeof query.status==="string"?{status:query.status}:{}),...(typeof query.from==="string"?{startedAt:{gte:new Date(query.from)}}:{})};const [runs,total]=await Promise.all([prisma.financialReconciliationRun.findMany({where,orderBy:{startedAt:"desc"},skip:(p.page-1)*p.limit,take:p.limit}),prisma.financialReconciliationRun.count({where})]);return{runs:runs.map(run=>({...run,failureReason:run.failureReason?.slice(0,500)??null})),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}};};
export const listAttentionSettlements=async(query:Record<string,unknown>,now=new Date())=>{const p=operationsPaging(query);const status=typeof query.status==="string"?query.status:undefined;const staleMinutes=query.staleMinutes===undefined?undefined:Number(query.staleMinutes);const where:Prisma.FinancialSettlementWhereInput={...(status?{status:status as never}:{status:{in:["PROVIDER_PROCESSING","UNKNOWN","FAILED","REVERSED"]}}),...(Number.isFinite(staleMinutes)?{updatedAt:{lt:cutoff(staleMinutes!,now)}}:{})};const [rows,total]=await Promise.all([prisma.financialSettlement.findMany({where,orderBy:{updatedAt:"asc"},skip:(p.page-1)*p.limit,take:p.limit}),prisma.financialSettlement.count({where})]);return{settlements:rows.map(row=>({id:row.id,organizationId:row.organizationId,walletAccountId:row.walletAccountId,sourceType:row.sourceType,sourceId:row.sourceId,amount:row.amount,currency:row.currency,method:row.method,provider:row.provider,providerReferenceFingerprint:fingerprint(row.providerTransferReference),status:row.status,providerStatus:row.providerStatus,reservation:{reservedAt:row.reservedAt,releasedAt:row.reservationReleasedAt},reconciliation:{attempts:row.reconciliationAttempts,claimedAt:row.reconciliationClaimedAt,leaseExpiresAt:row.reconciliationLeaseExpiresAt,lastError:row.lastReconciliationError?.slice(0,500)??null},updatedAt:row.updatedAt})),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}};};
export const listAttentionWebhooks=async(query:Record<string,unknown>)=>{const p=operationsPaging(query);const status=typeof query.status==="string"?query.status:undefined;const where:Prisma.ProviderWebhookEventWhereInput=status?{status}:{status:{in:["DEAD_LETTER","PROCESSING","FAILED"]}};const [rows,total]=await Promise.all([prisma.providerWebhookEvent.findMany({where,orderBy:{updatedAt:"desc"},skip:(p.page-1)*p.limit,take:p.limit,select:{id:true,provider:true,eventFingerprint:true,eventType:true,providerReference:true,status:true,attempts:true,deferredAttempts:true,nextAttemptAt:true,deadLetteredAt:true,failureReason:true,processingClaimedAt:true,processingLeaseExpiresAt:true,receivedAt:true,updatedAt:true}}),prisma.providerWebhookEvent.count({where})]);return{webhooks:rows.map(row=>({...row,providerReference:undefined,providerReferenceFingerprint:fingerprint(row.providerReference),failureReason:row.failureReason?.slice(0,500)??null})),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}};};
export const listInboundRecovery=async(query:Record<string,unknown>)=>{const p=operationsPaging(query);const kind=query.kind==="wallet-funding"?"wallet-funding":"subscription";const statuses=typeof query.status==="string"?[query.status]:["INITIALIZING","INITIALIZED","UNKNOWN","PROCESSING","FAILED"];if(kind==="subscription"){const [rows,total]=await Promise.all([prisma.subscriptionPaymentAttempt.findMany({where:{status:{in:statuses}},orderBy:{updatedAt:"asc"},skip:(p.page-1)*p.limit,take:p.limit}),prisma.subscriptionPaymentAttempt.count({where:{status:{in:statuses}}})]);return{kind,attempts:rows.map(row=>({id:row.id,organizationId:row.organizationId,operationType:row.operationType,amount:row.amount,currency:row.currency,provider:row.provider,referenceFingerprint:fingerprint(row.reference),status:row.status,reconciliationAttempts:row.reconciliationAttempts,claimedAt:row.reconciliationClaimedAt,leaseExpiresAt:row.reconciliationLeaseExpiresAt,deadLetteredAt:row.reconciliationDeadLetteredAt,lastError:(row.lastReconciliationError??row.failureReason)?.slice(0,500)??null,createdAt:row.createdAt,updatedAt:row.updatedAt})),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}};}const [rows,total]=await Promise.all([prisma.walletFundingAttempt.findMany({where:{status:{in:statuses}},orderBy:{updatedAt:"asc"},skip:(p.page-1)*p.limit,take:p.limit}),prisma.walletFundingAttempt.count({where:{status:{in:statuses}}})]);return{kind,attempts:rows.map(row=>({id:row.id,organizationId:row.organizationId,walletAccountId:row.walletAccountId,operationType:"WALLET_FUNDING",amount:row.amount,currency:row.currency,provider:row.provider,referenceFingerprint:fingerprint(row.reference),status:row.status,reconciliationAttempts:row.reconciliationAttempts,claimedAt:row.reconciliationClaimedAt,leaseExpiresAt:row.reconciliationLeaseExpiresAt,deadLetteredAt:row.reconciliationDeadLetteredAt,lastError:(row.lastReconciliationError??row.failureReason)?.slice(0,500)??null,createdAt:row.createdAt,updatedAt:row.updatedAt})),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}};};

export const triggerFinancialRecovery=async(user:AuthUser,provider?:SettlementProvider)=>{const requestId=crypto.randomUUID();await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM Organization WHERE id=${user.organizationId} FOR UPDATE`;await createAuditLog({organizationId:user.organizationId,actorUserId:user.id,action:"FINANCIAL_RECOVERY_REQUESTED",resource:"FINANCIAL_RECONCILIATION_RUN",resourceId:requestId,summary:"Requested bounded financial recovery",metadata:{trigger:"PLATFORM_ADMIN"}},tx);},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead,maxWait:20_000,timeout:60_000});return runFinancialRecovery({trigger:"PLATFORM_ADMIN",provider});};
export const requeueDeadLetterWebhook=async(id:string,user:AuthUser)=>prisma.$transaction(async tx=>{const row=await tx.providerWebhookEvent.findUnique({where:{id}});if(!row)throw notFound("Webhook event not found");if(row.status!=="DEAD_LETTER"){if(["FAILED","RECEIVED","PROCESSING"].includes(row.status))return row;throw conflict("Webhook event is not eligible for retry");}const claimed=await tx.providerWebhookEvent.updateMany({where:{id,status:"DEAD_LETTER"},data:{status:"FAILED",attempts:0,deadLetteredAt:null,nextAttemptAt:new Date(),failureReason:null,processingClaimToken:null,processingClaimedAt:null,processingLeaseExpiresAt:null}});if(!claimed.count)return tx.providerWebhookEvent.findUniqueOrThrow({where:{id}});const updated=await tx.providerWebhookEvent.findUniqueOrThrow({where:{id}});await createAuditLog({organizationId:user.organizationId,actorUserId:user.id,action:"FINANCIAL_WEBHOOK_REQUEUED",resource:"PROVIDER_WEBHOOK_EVENT",resourceId:id,summary:"Requeued durable dead-letter financial webhook",metadata:{provider:row.provider,eventType:row.eventType,eventFingerprint:row.eventFingerprint}},tx);return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead,maxWait:20_000,timeout:60_000});
