CREATE TABLE `PayrollEnrollment` (`id` VARCHAR(191) NOT NULL, `organizationId` VARCHAR(191) NOT NULL, `employeeId` VARCHAR(191) NOT NULL, `isActive` BOOLEAN NOT NULL DEFAULT true, `enrolledAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `enrolledById` VARCHAR(191) NULL, `removedAt` DATETIME(3) NULL, `removedById` VARCHAR(191) NULL, `removedReason` TEXT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `PayrollEnrollment_employeeId_key`(`employeeId`), INDEX `PayrollEnrollment_org_active_idx`(`organizationId`, `isActive`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `PayrollStatutoryProfile` (`id` VARCHAR(191) NOT NULL, `organizationId` VARCHAR(191) NOT NULL, `employeeId` VARCHAR(191) NOT NULL, `taxState` VARCHAR(191) NULL, `taxStatus` VARCHAR(191) NOT NULL DEFAULT 'PAYE', `tin` VARCHAR(191) NULL, `pensionPin` VARCHAR(191) NULL, `pfaName` VARCHAR(191) NULL, `nhfNumber` VARCHAR(191) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `PayrollStatutoryProfile_employeeId_key`(`employeeId`), INDEX `PayrollStatutoryProfile_org_tax_idx`(`organizationId`, `taxStatus`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `EmployeeDeduction` (`id` VARCHAR(191) NOT NULL, `organizationId` VARCHAR(191) NOT NULL, `employeeId` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `amount` DECIMAL(14,2) NOT NULL, `frequency` VARCHAR(191) NOT NULL DEFAULT 'MONTHLY', `active` BOOLEAN NOT NULL DEFAULT true, `effectiveFrom` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `effectiveTo` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, INDEX `EmployeeDeduction_org_employee_active_idx`(`organizationId`, `employeeId`, `active`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `EmployeeBenefitInKind` (`id` VARCHAR(191) NOT NULL, `organizationId` VARCHAR(191) NOT NULL, `employeeId` VARCHAR(191) NOT NULL, `hmoHealthInsurance` DECIMAL(14,2) NOT NULL DEFAULT 0, `airtimeAllowance` DECIMAL(14,2) NOT NULL DEFAULT 0, `mealAllowance` DECIMAL(14,2) NOT NULL DEFAULT 0, `thirteenthMonthAnnual` DECIMAL(14,2) NOT NULL DEFAULT 0, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `EmployeeBenefitInKind_employeeId_key`(`employeeId`), INDEX `EmployeeBenefitInKind_org_idx`(`organizationId`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `LoanAdvance` ADD COLUMN `loanType` VARCHAR(191) NOT NULL DEFAULT 'RECURRING', ADD COLUMN `monthlyRepayment` DECIMAL(14,2) NULL, ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE `SalaryStructure` ADD COLUMN `additionalAllowances` JSON NULL, ADD COLUMN `prorationResumeDate` DATETIME(3) NULL, ADD COLUMN `prorationMethod` VARCHAR(191) NULL;
ALTER TABLE `PayrollEnrollment` ADD CONSTRAINT `PayrollEnrollment_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `PayrollStatutoryProfile` ADD CONSTRAINT `PayrollStatutoryProfile_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EmployeeDeduction` ADD CONSTRAINT `EmployeeDeduction_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EmployeeBenefitInKind` ADD CONSTRAINT `EmployeeBenefitInKind_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `PayrollEnrollment` (`id`, `organizationId`, `employeeId`, `isActive`, `enrolledAt`, `createdAt`, `updatedAt`)
SELECT CONCAT('legacy-pe-', e.`id`), e.`organizationId`, e.`id`, true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `Employee` e WHERE e.`status` = 'ACTIVE' AND EXISTS (SELECT 1 FROM `SalaryStructure` s WHERE s.`employeeId` = e.`id`);
