import assert from "node:assert/strict";
import test from "node:test";
import { Prisma } from "@prisma/client";
import { analyzeWalletIntegrity } from "./core/financial-integrity-scanner";

const money=(v:string|number)=>new Prisma.Decimal(v);
const row=(id:string,amount:string,before:string,after:string,extra:Record<string,unknown>={})=>({id,organizationId:"org",walletAccountId:"wallet",payrollRunId:null,taxRemittanceId:null,type:"FUNDING",direction:"CREDIT",amount:money(amount),balanceBefore:money(before),balanceAfter:money(after),reference:`ref-${id}`,transferReference:`transfer-${id}`,description:"fixture",sourceType:null,sourceId:null,reversalOfId:null,createdById:null,createdAt:new Date(`2026-09-23T00:00:0${id}.000Z`),...extra}) as any;
const wallet=(balance:string,transactions:any[],reserved="0",settlements:any[]=[],classification="CUSTOMER")=>({id:"wallet",organizationId:"org",balance:money(balance),reservedBalance:money(reserved),currency:"NGN",transactions,settlements,organization:{classification}}) as any;
const categories=(w:any)=>new Set(analyzeWalletIntegrity(w).map(x=>x.category));

test("healthy Decimal wallet produces no finding",()=>assert.equal(analyzeWalletIntegrity(wallet("100.30",[row("1","100.30","0","100.30")])).length,0));
test("stored balances above and below reconstruction are detected",()=>{assert.ok(categories(wallet("101",[row("1","100","0","100")])).has("UNLEDGERED_WALLET_VALUE"));assert.ok(categories(wallet("99",[row("1","100","0","100")])).has("WALLET_BALANCE_MISMATCH"));});
test("running balance break and duplicate evidence are detected",()=>{const a=row("1","50","0","50");const b=row("2","50","60","110",{transferReference:a.transferReference});const c=categories(wallet("100",[a,b]));assert.ok(c.has("LEDGER_RUNNING_BALANCE_BREAK"));assert.ok(c.has("DUPLICATE_FINANCIAL_EVIDENCE"));});
test("reservation mismatch and orphaned failed reservation are detected",()=>{const settlement={id:"s",organizationId:"org",walletAccountId:"wallet",sourceType:"X",sourceId:"x",method:"PROVIDER",status:"FAILED",amount:money(20),currency:"NGN",reservedAt:new Date(),reservationReleasedAt:null};const c=categories(wallet("100",[row("1","100","0","100")],"20",[settlement]));assert.ok(c.has("WALLET_RESERVED_BALANCE_MISMATCH"));assert.ok(c.has("ORPHANED_RESERVATION"));});
test("successful settlement requires one debit while manual success needs no provider reference",()=>{const settlement={id:"s",organizationId:"org",walletAccountId:"wallet",sourceType:"PAYMENT_REQUEST",sourceId:"p",method:"MANUAL",status:"SUCCEEDED",amount:money(10),currency:"NGN",reservedAt:new Date(),reservationReleasedAt:new Date(),providerTransferReference:null,reversalLedgerId:null};const c=categories(wallet("100",[row("1","100","0","100")],"0",[settlement]));assert.ok(c.has("SETTLEMENT_MARKED_SUCCESS_WITHOUT_REQUIRED_DEBIT"));assert.ok(!c.has("PROVIDER_REFERENCE_MISMATCH"));});
test("provider lifecycle requires durable reference",()=>{const settlement={id:"s",organizationId:"org",walletAccountId:"wallet",sourceType:"X",sourceId:"x",method:"PROVIDER",status:"UNKNOWN",amount:money(10),currency:"NGN",reservedAt:new Date(),reservationReleasedAt:null,providerTransferReference:null};assert.ok(categories(wallet("100",[row("1","100","0","100")],"10",[settlement])).has("PROVIDER_REFERENCE_MISMATCH"));});
test("TEST_E2E credit is valid only for TEST_E2E organization",()=>{const tx=row("1","100","0","100",{type:"TEST_E2E_CREDIT"});assert.ok(categories(wallet("100",[tx])).has("INVALID_TEST_E2E_FINANCIAL_EVIDENCE"));assert.ok(!categories(wallet("100",[tx],"0",[],"TEST_E2E")).has("INVALID_TEST_E2E_FINANCIAL_EVIDENCE"));});
test("repaired historical wallet has no unexplained, running-balance, business debit or settlement finding",()=>{const rows=[row("1","250000","0","250000"),row("2","1000","250000","251000"),row("3","300000","251000","551000"),row("4","300000","851000","1151000"),row("5","300000","1151000","1451000"),row("6","30000","1481000","1511000"),row("7","2000","1541000","1543000"),row("8","1000","1545000","1546000")];rows.push(row("9","362000","1546000","1184000",{type:"FINANCIAL_INTEGRITY_CORRECTION",direction:"ADJUSTMENT",sourceType:"FINANCIAL_INTEGRITY_REPAIR",sourceId:"PAYROLL-WALLET-ATOMICITY-2026-09-23-001",transferReference:null}));const findings=analyzeWalletIntegrity(wallet("1184000",rows));assert.deepEqual(findings,[]);});
